#!/bin/sh

dir_project="/root/mojito-base/mojito-note"

if [ ! -d $dir_project ]; then
    mkdir -p $dir_project
    echo -e "\033[32m this is $dir_project success ! \033[0m"
    cd $dir_project
    git clone
fi
